### ISSUE TITLE
audio sampling error

### ISSUE THREAD

**Issue by oladipoacademics** [ericgibert/supersid#10]
hi, i tried to run supersid.py on raspberry pi 3 but i keep getting this error. i  have install pyalsaaudio but this message would not clear. pls help
From Sampler object instance:
Could not open capture device. Please cError alsaaudio
global name 'alsaaudio_soundcard' is not defined
To debugg: remove the try/except clause to get detail on what exception is triggered.
Traceback (most recent call last):
  File "supersid.py", line 226, in <module>
    sid = SuperSID(config_file=args.config_file, read_file=args.filename)
  File "supersid.py", line 100, in __init__
    self.close()
  File "supersid.py", line 188, in close
    self.sampler.close()
  File "/home/pi/Desktop/supersid-master/supersid/sampler.py", line 221, in close
    self.capture_device.close()
AttributeError: Sampler instance has no attribute 'capture_device'

**Comment by jrhilton** [comment]
What soundcard are you using and is it set to be the default one? I've seen similar messages when the built in sound-out-only (HDMI or headphone jack) was the default card still.
